name: CI/CD Pipeline for Express App

on:
  push:
    branches:
      - master  # Trigger the pipeline on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t express-app .

      - name: Tag Docker image for ECR
        run: |
          docker tag express-app:latest <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/express-app:latest

      - name: Push Docker image to ECR
        run: |
          docker push <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/express-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2 (SSH)
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Stop existing container
            sudo docker stop express-app
            sudo docker rm express-app
            
            # Pull the latest image from ECR
            sudo docker pull <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/express-app:latest

            # Run the new container
            sudo docker run -d -p 80:3000 --name express-app <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/express-app:latest
